# Generated by Django 2.0.5 on 2018-05-31 18:50

from django.db import migrations, models
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', django_grapesjs.models.fields.GrapesJsHtmlField()),
            ],
        ),
    ]
