# Generated by Django 2.2.5 on 2019-10-06 15:10

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django_grapesjs.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrapesJSJSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gjs_assets', django.contrib.postgres.fields.hstore.HStoreField()),
                ('gjs_css', django.contrib.postgres.fields.hstore.HStoreField()),
                ('gjs_styles', django.contrib.postgres.fields.hstore.HStoreField()),
                ('gjs_html', django.contrib.postgres.fields.hstore.HStoreField()),
                ('gjs_components', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'verbose_name': 'grapes model',
                'verbose_name_plural': 'grapesjs models',
            },
        ),
        migrations.CreateModel(
            name='GrapesJSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', django_grapesjs.models.fields.GrapesJsHtmlField()),
            ],
        ),
    ]
